-------------------- Log Start | Wed May 15 23:49:33 2024 --------------------
data_path: /home/pi/printer_data
is_default_data_path: False
config_file: /home/pi/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 215a8ff9406149558f7a7b86cec4267d
unix_socket_path: /home/pi/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/pi/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/pi/moonraker-env/bin/python /home/pi/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
enable_debug_logging = False
max_upload_size = 1024
klippy_uds_address = home/pi/printer_data/comms/klippy.sock

[file_manager]
config_path = ~/printer_data/config
enable_object_processing = True

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://app.fluidd.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.1.0/24
	172.16.0.0/24
	172.17.0.15:80
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[update_manager]
refresh_interval = 168
enable_auto_refresh = True
enable_repo_debug = True

[update_manager mainsail]
type = web
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager beacon]
type = git_repo
channel = dev
path = ~/beacon_klipper
origin = https://github.com/beacon3d/beacon_klipper.git
env = ~/klippy-env/bin/python
requirements = requirements.txt
install_script = install.sh
is_system_service = False
managed_services = klipper
info_tags = 
	desc=Beacon Surface Scanner

[wled lights]
type = http
address = 192.168.1.7
initial_preset = 2
initial_red = 1
initial_green = 1
initial_blue = 1
chain_count = 115

#################################################################
All Configuration Files:
/home/pi/printer_data/config/moonraker.conf
#################################################################

Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 4

System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 735411d3
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.3
  total_memory: 880328
  memory_units: kB

***sd_info***
  manufacturer_id: 27
  manufacturer: Unknown
  oem_id: 5048
  product_name: SD32G
  product_revision: 6.0
  serial_number: 79550c64
  manufacturer_date: 8/2021
  capacity: 28.8 GiB
  total_bytes: 30941380608

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'network-online.target', 'sysinit.target']
**After=['network-online.target', 'basic.target', 'klipper.service', 'systemd-journald.socket', 'system.slice', 'sysinit.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/pi/printer_data/systemd/moonraker.env
**ExecStart=/home/pi/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=pi

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice', '-.mount']
**After=['-.mount', 'system.slice', 'network-online.target', 'basic.target', 'sysinit.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/pi/printer_data/systemd/klipper.env
**ExecStart=/home/pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=pi
Git Repo moonraker: Warnings detected:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
Git Repo klipper: Warnings detected:
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
Git Repo beacon: Warnings detected:
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
Klipper Version: v0.12.0-85-gd785b396-dirty
CPU Throttled Flags: ['Previously Temperature Limited']
2024-05-16 00:49:33,489 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.8
2024-05-16 00:49:33,492 [application.py:log_request()] - 101 GET /websocket (192.168.1.8) [_TRUSTED_USER_] 4.32ms
2024-05-16 00:49:33,492 [websockets.py:open()] - Websocket Opened: ID: 548236300144, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36, Host Name: 192.168.1.28
2024-05-16 00:49:35,531 [file_manager.py:get_file_list()] - Updating File List <config>...
2024-05-16 00:49:35,704 [websockets.py:on_close()] - Websocket Closed: ID: 548236300144 Close Code: None, Close Reason: None, Pong Time Elapsed: 2.22
2024-05-16 00:49:37,283 [application.py:log_request()] - 101 GET /websocket (192.168.1.8) [_TRUSTED_USER_] 3.01ms
2024-05-16 00:49:37,284 [websockets.py:open()] - Websocket Opened: ID: 548236299904, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36, Host Name: 192.168.1.28
2024-05-16 00:49:37,315 [file_manager.py:get_file_list()] - Updating File List <config>...
2024-05-16 00:50:10,843 [application.py:log_request()] - 101 GET /websocket (192.168.1.8) [_TRUSTED_USER_] 3.27ms
2024-05-16 00:50:10,844 [websockets.py:open()] - Websocket Opened: ID: 548237077904, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36, Host Name: 192.168.1.28
2024-05-16 00:50:10,852 [websockets.py:_handle_identify()] - Websocket 548237077904 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-05-16 01:53:02,706 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.8
2024-05-16 01:53:02,769 [websockets.py:on_close()] - Websocket Closed: ID: 548237077904 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.92
2024-05-16 01:53:02,771 [websockets.py:on_close()] - Websocket Closed: ID: 548236299904 Close Code: None, Close Reason: None, Pong Time Elapsed: 5.48
2024-05-16 01:56:30,264 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.8
2024-05-16 01:56:30,268 [application.py:log_request()] - 101 GET /websocket (192.168.1.8) [_TRUSTED_USER_] 6.35ms
2024-05-16 01:56:30,269 [websockets.py:open()] - Websocket Opened: ID: 548226174688, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36, Host Name: 192.168.1.28
2024-05-16 01:56:30,364 [websockets.py:_handle_identify()] - Websocket 548226174688 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-05-16 02:58:02,719 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.8
2024-05-16 06:52:51,041 [server.py:_handle_term_signal()] - Exiting with signal SIGTERM
2024-05-16 06:52:51,052 [websockets.py:on_close()] - Websocket Closed: ID: 548236165376 Close Code: None, Close Reason: None, Pong Time Elapsed: 10.06
2024-05-16 06:52:51,160 [websockets.py:on_close()] - Websocket Closed: ID: 548226174688 Close Code: 1001, Close Reason: Server Shutdown, Pong Time Elapsed: 0.88
2024-05-16 06:52:51,263 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-05-16 06:52:52,606 [database.py:close()] - Database statistics:

announcements:
psize: 4096
depth: 0
branch_pages: 0
leaf_pages: 0
overflow_pages: 0
entries: 0
authorized_users:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
gcode_metadata:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 3
history:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 4
overflow_pages: 0
entries: 12
mainsail:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 2
overflow_pages: 0
entries: 9
moonraker:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 7
update_manager:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 6
entries: 5
2024-05-16 06:52:57,555 [server.py:main()] - Server Shutdown
-------------------- Log Start | Thu May 16 05:53:28 2024 --------------------
data_path: /home/pi/printer_data
is_default_data_path: False
config_file: /home/pi/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 215a8ff9406149558f7a7b86cec4267d
unix_socket_path: /home/pi/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/pi/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/pi/moonraker-env/bin/python /home/pi/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2024-05-16 06:53:28,300 [confighelper.py:read_file()] - Configuration File '/home/pi/printer_data/config/moonraker.conf' parsed, total size: 1762 B
2024-05-16 06:53:28,301 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
enable_debug_logging = False
max_upload_size = 1024
klippy_uds_address = home/pi/printer_data/comms/klippy.sock

[file_manager]
config_path = ~/printer_data/config
enable_object_processing = True

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://app.fluidd.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.1.0/24
	172.16.0.0/24
	172.17.0.15:80
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[update_manager]
refresh_interval = 168
enable_auto_refresh = True
enable_repo_debug = True

[update_manager mainsail]
type = web
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager beacon]
type = git_repo
channel = dev
path = ~/beacon_klipper
origin = https://github.com/beacon3d/beacon_klipper.git
env = ~/klippy-env/bin/python
requirements = requirements.txt
install_script = install.sh
is_system_service = False
managed_services = klipper
info_tags = 
	desc=Beacon Surface Scanner

[wled lights]
type = http
address = 192.168.1.7
initial_preset = 2
initial_red = 1
initial_green = 1
initial_blue = 1
chain_count = 115

#################################################################
All Configuration Files:
/home/pi/printer_data/config/moonraker.conf
#################################################################
2024-05-16 06:53:28,302 [server.py:add_warning()] - [server]: Option 'enable_debug_logging' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
2024-05-16 06:53:28,961 [server.py:load_component()] - Component (secrets) loaded
2024-05-16 06:53:28,978 [server.py:load_component()] - Component (template) loaded
2024-05-16 06:53:28,996 [server.py:load_component()] - Component (klippy_connection) loaded
2024-05-16 06:53:30,751 [server.py:load_component()] - Component (application) loaded
2024-05-16 06:53:30,818 [server.py:load_component()] - Component (websockets) loaded
2024-05-16 06:53:30,971 [server.py:load_component()] - Component (dbus_manager) loaded
2024-05-16 06:53:31,047 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 4
2024-05-16 06:53:31,087 [server.py:load_component()] - Component (database) loaded
2024-05-16 06:53:31,140 [file_manager.py:__init__()] - Using File System Observer: inotify
2024-05-16 06:53:31,238 [server.py:add_warning()] - [file_manager]: Option 'config_path' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
2024-05-16 06:53:31,256 [server.py:load_component()] - Component (file_manager) loaded
2024-05-16 06:53:31,278 [server.py:load_component()] - Component (klippy_apis) loaded
2024-05-16 06:53:31,866 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 735411d3
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.3
  total_memory: 880332
  memory_units: kB

***sd_info***
  manufacturer_id: 27
  manufacturer: Unknown
  oem_id: 5048
  product_name: SD32G
  product_revision: 6.0
  serial_number: 79550c64
  manufacturer_date: 8/2021
  capacity: 28.8 GiB
  total_bytes: 30941380608

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2024-05-16 06:53:31,887 [server.py:load_component()] - Component (shell_command) loaded
2024-05-16 06:53:31,888 [machine.py:__init__()] - Using System Provider: systemd_dbus
2024-05-16 06:53:31,902 [server.py:load_component()] - Component (machine) loaded
2024-05-16 06:53:31,915 [server.py:load_component()] - Component (data_store) loaded
2024-05-16 06:53:31,939 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2024-05-16 06:53:31,941 [server.py:load_component()] - Component (proc_stats) loaded
2024-05-16 06:53:31,950 [server.py:load_component()] - Component (job_state) loaded
2024-05-16 06:53:31,964 [server.py:load_component()] - Component (job_queue) loaded
2024-05-16 06:53:32,026 [server.py:load_component()] - Component (http_client) loaded
2024-05-16 06:53:32,042 [server.py:load_component()] - Component (announcements) loaded
2024-05-16 06:53:32,052 [server.py:load_component()] - Component (webcam) loaded
2024-05-16 06:53:32,066 [server.py:load_component()] - Component (extensions) loaded
2024-05-16 06:53:32,141 [server.py:add_warning()] - [authorization]: Invalid domain name '172.17.0.15:80' in option 'trusted_clients'
2024-05-16 06:53:32,143 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.1.0/24
172.16.0.0/24
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://app\.fluidd\.xyz
http://.*\.local
http://.*\.lan
2024-05-16 06:53:32,153 [server.py:load_component()] - Component (authorization) loaded
2024-05-16 06:53:32,207 [wled.py:__init__()] - WLED component loading strips: ['wled lights']
2024-05-16 06:53:32,207 [wled.py:__init__()] - WLED strip: lights
2024-05-16 06:53:32,216 [server.py:load_component()] - Component (wled) loaded
2024-05-16 06:53:32,226 [server.py:load_component()] - Component (history) loaded
2024-05-16 06:53:32,347 [server.py:add_warning()] - [update_manager]: Option 'enable_repo_debug' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
2024-05-16 06:53:32,353 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/pi/moonraker-env
2024-05-16 06:53:32,390 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/pi/klippy-env
2024-05-16 06:53:32,396 [base_deploy.py:log_info()] - Git Repo beacon: Option 'env' is deprecated, use 'virtualenv' instead.
2024-05-16 06:53:32,398 [base_deploy.py:log_info()] - Git Repo beacon: Detected virtualenv: /home/pi/klippy-env
2024-05-16 06:53:32,407 [server.py:load_component()] - Component (update_manager) loaded
2024-05-16 06:53:32,421 [server.py:load_component()] - Component (octoprint_compat) loaded
2024-05-16 06:53:32,424 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2024-05-16 06:53:32,454 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2024-05-16 06:53:32,526 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2024-05-16 06:53:32,526 [machine.py:validation_init()] - Installation version in database up to date
2024-05-16 06:53:33,476 [machine.py:check_virt_status()] - No Virtualization Detected
2024-05-16 06:53:33,504 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.28
2024-05-16 06:53:33,510 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.28
2024-05-16 06:53:33,644 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'network-online.target', 'sysinit.target']
**After=['system.slice', 'klipper.service', 'basic.target', 'systemd-journald.socket', 'sysinit.target', 'network-online.target']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/pi/printer_data/systemd/moonraker.env
**ExecStart=/home/pi/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=pi
2024-05-16 06:53:33,644 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2024-05-16 06:53:33,645 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2024-05-16 06:53:33,651 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2024-05-16 06:53:33,651 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.28
2024-05-16 06:53:33,653 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2024-05-16 06:53:33,654 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'system.slice', '-.mount']
**After=['-.mount', 'system.slice', 'network-online.target', 'basic.target', 'sysinit.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/pi/printer_data/systemd/klipper.env
**ExecStart=/home/pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=pi
2024-05-16 06:53:33,654 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2024-05-16 06:53:33,654 [server.py:_initialize_component()] - Performing Component Post Init: [wled]
2024-05-16 06:53:33,656 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2024-05-16 06:53:33,659 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2024-05-16 06:53:34,833 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2024-05-16 06:53:34,883 [git_deploy.py:log_repo_info()] - Git Repo moonraker Detected:
Owner: Arksine
Repository Name: moonraker
Path: /home/pi/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Recovery URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Upstream Commit SHA: ba9428558adc70ed8cb3cdcea1723358ead23741
Current Version: v0.8.0-268-ga23187b4
Upstream Version: v0.8.0-354-gba942855
Rollback Commit: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Rollback Branch: master
Rollback Version: v0.8.0-268-ga23187b4
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 86
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
2024-05-16 06:53:34,938 [git_deploy.py:log_repo_info()] - Git Repo klipper Detected:
Owner: Klipper3d
Repository Name: klipper
Path: /home/pi/klipper
Remote: origin
Branch: master
Remote URL: https://github.com/Klipper3d/klipper.git
Recovery URL: https://github.com/Klipper3d/klipper.git
Current Commit SHA: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Upstream Commit SHA: 434770eaf9d382cccba203a3475ace2dc0653d7b
Current Version: v0.12.0-85-gd785b396
Upstream Version: v0.12.0-179-g434770ea
Rollback Commit: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Rollback Branch: master
Rollback Version: v0.12.0-85-gd785b396
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 94
Diverged: False
Repo Warnings:
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
2024-05-16 06:53:34,954 [web_deploy.py:_log_client_info()] - Web Client mainsail Detected:
Repo: mainsail-crew/mainsail
Channel: stable
Path: /home/pi/mainsail
Local Version: v2.9.1
Remote Version: v2.11.2
Valid: True
Fallback Client Detected: False
Pre-release: False
Download Url: https://github.com/mainsail-crew/mainsail/releases/download/v2.11.2/mainsail.zip
Download Size: 2114797
Content Type: application/zip
Rollback Version: v2.9.1
Rollback Repo: mainsail-crew/mainsail
2024-05-16 06:53:35,018 [git_deploy.py:log_repo_info()] - Git Repo beacon Detected:
Owner: beacon3d
Repository Name: beacon_klipper
Path: /home/pi/beacon_klipper
Remote: origin
Branch: master
Remote URL: https://github.com/beacon3d/beacon_klipper.git
Recovery URL: https://github.com/beacon3d/beacon_klipper.git
Current Commit SHA: b89bbbec0d94c92ba709a1da283afd0a5eb2c19e
Upstream Commit SHA: b89bbbec0d94c92ba709a1da283afd0a5eb2c19e
Current Version: v1.0.0-35-gb89bbbec
Upstream Version: v1.0.0-35-gb89bbbec
Rollback Commit: b89bbbec0d94c92ba709a1da283afd0a5eb2c19e
Rollback Branch: master
Rollback Version: v1.0.0-35-gb89bbbec
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 0
Diverged: False
Repo Warnings:
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
2024-05-16 06:53:35,022 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/pi/printer_data/comms/moonraker.sock'
2024-05-16 06:53:35,025 [base_deploy.py:log_info()] - PackageKit: Next refresh in: 2 Days, 23 Hours, 56 Minutes, 31 Seconds
2024-05-16 06:53:35,025 [base_deploy.py:log_info()] - Git Repo moonraker: Next refresh in: 2 Days, 23 Hours, 56 Minutes, 43 Seconds
2024-05-16 06:53:35,025 [base_deploy.py:log_info()] - Git Repo klipper: Next refresh in: 2 Days, 23 Hours, 56 Minutes, 54 Seconds
2024-05-16 06:53:35,025 [base_deploy.py:log_info()] - Web Client mainsail: Next refresh in: 3 Days, 9 Hours, 1 Minute, 5 Seconds
2024-05-16 06:53:35,026 [base_deploy.py:log_info()] - Git Repo beacon: Next refresh in: 3 Days, 9 Hours, 15 Minutes, 40 Seconds
2024-05-16 06:53:35,026 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: mainsailos
2024-05-16 06:53:35,030 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2024-05-16 06:53:35,283 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-05-16 06:53:35,406 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target', '-.mount']
**After=['basic.target', 'system.slice', 'network-online.target', '-.mount', 'sysinit.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/pi/printer_data/systemd/klipper.env
**ExecStart=/home/pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=pi
2024-05-16 06:53:35,662 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396-dirty
2024-05-16 06:53:35,986 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2024-05-16 06:53:36,012 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 4.47ms
2024-05-16 06:53:36,014 [websockets.py:open()] - Websocket Opened: ID: 547585879920, Proxied: False, User Agent: , Host Name: 127.0.0.1
2024-05-16 06:53:36,023 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.127
2024-05-16 06:53:36,026 [application.py:log_request()] - 101 GET /websocket (192.168.1.127) [_TRUSTED_USER_] 8.11ms
2024-05-16 06:53:36,027 [websockets.py:open()] - Websocket Opened: ID: 547585926288, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36, Host Name: 192.168.1.28
2024-05-16 06:53:36,042 [websockets.py:_handle_identify()] - Websocket 547585926288 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-05-16 06:53:36,671 [websockets.py:_handle_identify()] - Websocket 547585879920 Client Identified - Name: KlipperScreen, Version: v0.4.0-73-g1afc67b, Type: display
2024-05-16 06:53:37,312 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.149
2024-05-16 06:53:40,209 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-05-16 06:53:40,232 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-05-16 06:53:40,283 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2024-05-16 06:53:40,468 [job_state.py:_handle_started()] - Job state initialized: standby
2024-05-16 06:53:40,747 [klippy_connection.py:_check_ready()] - Klippy ready
2024-05-16 06:53:56,003 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'temperature_sensor mcu', 'temperature_sensor raspi', 'temperature_sensor toolhead', 'temperature_sensor chamber', 'temperature_sensor beacon_coil', 'extruder']
2024-05-16 06:54:19,090 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 58.69ms
2024-05-16 06:54:49,034 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.33ms
2024-05-16 06:55:19,033 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.42ms
2024-05-16 06:55:49,029 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.42ms
2024-05-16 06:56:19,031 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.52ms
2024-05-16 06:56:49,032 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.68ms
2024-05-16 06:57:19,034 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.80ms
2024-05-16 06:57:49,034 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.57ms
2024-05-16 06:58:19,038 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.94ms
2024-05-16 06:58:49,070 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 9.08ms
2024-05-16 06:59:19,033 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.35ms
2024-05-16 06:59:49,038 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.12ms
2024-05-16 07:00:19,037 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.80ms
2024-05-16 07:00:49,037 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.83ms
2024-05-16 07:01:19,040 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.91ms
2024-05-16 07:01:49,046 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.01ms
2024-05-16 07:02:19,041 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.04ms
2024-05-16 07:02:49,043 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.84ms
2024-05-16 07:03:19,042 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.19ms
2024-05-16 07:03:49,050 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.72ms
2024-05-16 07:04:19,046 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.26ms
2024-05-16 07:04:49,045 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.13ms
2024-05-16 07:05:19,057 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.03ms
2024-05-16 07:05:49,048 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 07:06:19,051 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.24ms
2024-05-16 07:06:49,055 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.27ms
2024-05-16 07:07:19,053 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.10ms
2024-05-16 07:07:49,054 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.06ms
2024-05-16 07:08:19,059 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 07:08:49,066 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.23ms
2024-05-16 07:09:19,057 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 07:09:49,064 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.88ms
2024-05-16 07:10:19,064 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.31ms
2024-05-16 07:10:49,061 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.11ms
2024-05-16 07:11:19,068 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.74ms
2024-05-16 07:11:49,065 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.26ms
2024-05-16 07:12:19,064 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.88ms
2024-05-16 07:12:49,070 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.77ms
2024-05-16 07:13:19,066 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.11ms
2024-05-16 07:13:49,071 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 07:14:19,074 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.38ms
2024-05-16 07:14:49,086 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.42ms
2024-05-16 07:15:19,082 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.77ms
2024-05-16 07:15:49,087 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.83ms
2024-05-16 07:16:19,069 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.01ms
2024-05-16 07:16:49,079 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.23ms
2024-05-16 07:17:19,074 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.00ms
2024-05-16 07:17:49,075 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.72ms
2024-05-16 07:18:19,084 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.01ms
2024-05-16 07:18:49,075 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.26ms
2024-05-16 07:19:19,079 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.28ms
2024-05-16 07:19:49,078 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.99ms
2024-05-16 07:20:19,083 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.62ms
2024-05-16 07:20:49,080 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 07:21:19,081 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.39ms
2024-05-16 07:21:49,090 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.79ms
2024-05-16 07:22:19,080 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.06ms
2024-05-16 07:22:49,084 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.91ms
2024-05-16 07:23:19,084 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 07:23:49,083 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.15ms
2024-05-16 07:24:19,091 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.79ms
2024-05-16 07:24:49,088 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.82ms
2024-05-16 07:25:19,087 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.28ms
2024-05-16 07:25:49,087 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.15ms
2024-05-16 07:26:19,089 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.94ms
2024-05-16 07:26:49,088 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.18ms
2024-05-16 07:27:19,089 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.82ms
2024-05-16 07:27:49,376 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.12ms
2024-05-16 07:28:19,193 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 10.22ms
2024-05-16 07:28:21,754 [server.py:add_log_rollover_item()] - CPU Throttled Flags: ['Temperature Limit Active', 'Previously Temperature Limited']
2024-05-16 07:28:25,813 [machine.py:_parse_network_interfaces()] - Error processing network update
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/machine.py", line 630, in _parse_network_interfaces
    resp = await self.addr_cmd.run_with_response(log_complete=False)
  File "/home/pi/moonraker/moonraker/components/shell_command.py", line 277, in run_with_response
    raise ShellCommandError(
moonraker.components.shell_command.ShellCommandError: Error running shell command: 'ip -json -det address'
2024-05-16 07:28:49,105 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.88ms
2024-05-16 07:29:19,096 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.47ms
2024-05-16 07:29:49,098 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.28ms
2024-05-16 07:30:19,098 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.33ms
2024-05-16 07:30:49,101 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.73ms
2024-05-16 07:31:19,099 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.10ms
2024-05-16 07:31:49,103 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.07ms
2024-05-16 07:32:19,101 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.26ms
2024-05-16 07:32:49,103 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.26ms
2024-05-16 07:33:19,105 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.61ms
2024-05-16 07:33:49,108 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.48ms
2024-05-16 07:34:19,119 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 10.57ms
2024-05-16 07:34:49,109 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.81ms
2024-05-16 07:35:19,114 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.72ms
2024-05-16 07:35:49,118 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.75ms
2024-05-16 07:36:19,124 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.28ms
2024-05-16 07:36:49,114 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.08ms
2024-05-16 07:37:19,113 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.36ms
2024-05-16 07:37:49,112 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 07:38:19,112 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.57ms
2024-05-16 07:38:49,345 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.63ms
2024-05-16 07:39:19,118 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.23ms
2024-05-16 07:39:49,120 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.20ms
2024-05-16 07:40:19,114 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.17ms
2024-05-16 07:40:49,117 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.65ms
2024-05-16 07:41:19,118 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.96ms
2024-05-16 07:41:49,119 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 07:42:19,121 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.90ms
2024-05-16 07:42:49,121 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.01ms
2024-05-16 07:43:19,121 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.30ms
2024-05-16 07:43:49,133 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.27ms
2024-05-16 07:44:19,125 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.54ms
2024-05-16 07:44:49,125 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.27ms
2024-05-16 07:45:19,137 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.15ms
2024-05-16 07:45:49,124 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.26ms
2024-05-16 07:46:19,126 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.50ms
2024-05-16 07:46:49,128 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.70ms
2024-05-16 07:47:19,129 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.09ms
2024-05-16 07:47:49,129 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.80ms
2024-05-16 07:48:19,131 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.60ms
2024-05-16 07:48:49,131 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.30ms
2024-05-16 07:49:19,129 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.31ms
2024-05-16 07:49:49,130 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.54ms
2024-05-16 07:50:19,356 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.48ms
2024-05-16 07:50:49,132 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.15ms
2024-05-16 07:51:19,134 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.31ms
2024-05-16 07:51:49,143 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.17ms
2024-05-16 07:52:19,136 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.20ms
2024-05-16 07:52:49,139 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.33ms
2024-05-16 07:53:19,149 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.87ms
2024-05-16 07:53:49,145 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.20ms
2024-05-16 07:54:19,373 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.36ms
2024-05-16 07:54:49,145 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.71ms
2024-05-16 07:55:19,141 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.39ms
2024-05-16 07:55:49,140 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.28ms
2024-05-16 07:56:19,142 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.16ms
2024-05-16 07:56:49,370 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.42ms
2024-05-16 07:57:19,144 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.59ms
2024-05-16 07:57:49,146 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.44ms
2024-05-16 07:58:19,161 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.27ms
2024-05-16 07:58:48,436 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.127
2024-05-16 07:58:49,145 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.17ms
2024-05-16 07:59:19,148 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.93ms
2024-05-16 07:59:49,145 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.30ms
2024-05-16 08:00:19,152 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.79ms
2024-05-16 08:00:49,148 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.54ms
2024-05-16 08:01:19,154 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.24ms
2024-05-16 08:01:49,152 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.45ms
2024-05-16 08:02:19,152 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.50ms
2024-05-16 08:02:49,154 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.88ms
2024-05-16 08:03:19,163 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.72ms
2024-05-16 08:03:49,152 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.76ms
2024-05-16 08:04:19,154 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 08:04:49,157 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.23ms
2024-05-16 08:05:19,157 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.89ms
2024-05-16 08:05:49,156 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.83ms
2024-05-16 08:06:19,160 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.87ms
2024-05-16 08:06:49,170 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.80ms
2024-05-16 08:07:19,160 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.48ms
2024-05-16 08:07:49,166 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.38ms
2024-05-16 08:08:19,162 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.95ms
2024-05-16 08:08:49,160 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 08:09:19,160 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.33ms
2024-05-16 08:09:49,163 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.35ms
2024-05-16 08:10:19,163 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.79ms
2024-05-16 08:10:49,167 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.75ms
2024-05-16 08:11:19,166 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.54ms
2024-05-16 08:11:50,173 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.99ms
2024-05-16 08:12:19,168 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.68ms
2024-05-16 08:12:49,168 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.17ms
2024-05-16 08:13:19,167 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.52ms
2024-05-16 08:13:49,182 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 9.62ms
2024-05-16 08:14:19,166 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.94ms
2024-05-16 08:14:49,169 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.71ms
2024-05-16 08:15:19,170 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.80ms
2024-05-16 08:15:49,169 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.21ms
2024-05-16 08:16:19,178 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.89ms
2024-05-16 08:16:49,169 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.60ms
2024-05-16 08:17:19,171 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.11ms
2024-05-16 08:17:49,170 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.80ms
2024-05-16 08:18:19,174 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.49ms
2024-05-16 08:18:49,173 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.09ms
2024-05-16 08:19:19,176 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.78ms
2024-05-16 08:19:49,178 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.92ms
2024-05-16 08:20:19,179 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.86ms
2024-05-16 08:20:49,178 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.20ms
2024-05-16 08:21:19,177 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.58ms
2024-05-16 08:21:49,180 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.92ms
2024-05-16 08:22:19,181 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.95ms
2024-05-16 08:22:49,182 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.55ms
2024-05-16 08:23:19,182 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.69ms
2024-05-16 08:23:49,191 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.79ms
2024-05-16 08:24:19,186 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.74ms
2024-05-16 08:24:49,187 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.62ms
2024-05-16 08:25:19,201 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.01ms
2024-05-16 08:25:49,187 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.96ms
2024-05-16 08:26:19,191 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.96ms
2024-05-16 08:26:49,190 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 08:27:19,201 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.51ms
2024-05-16 08:27:49,193 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.91ms
2024-05-16 08:28:19,194 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.04ms
2024-05-16 08:28:49,193 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.91ms
2024-05-16 08:29:19,200 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.50ms
2024-05-16 08:29:49,198 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.10ms
2024-05-16 08:30:19,235 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.03ms
2024-05-16 08:30:49,201 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.84ms
2024-05-16 08:31:19,206 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.90ms
2024-05-16 08:31:49,208 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.97ms
2024-05-16 08:32:19,205 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.09ms
2024-05-16 08:32:49,207 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.97ms
2024-05-16 08:33:19,213 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.48ms
2024-05-16 08:33:49,207 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.73ms
2024-05-16 08:34:19,212 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.69ms
2024-05-16 08:34:49,215 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.72ms
2024-05-16 08:35:19,213 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.62ms
2024-05-16 08:35:49,212 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.54ms
2024-05-16 08:36:19,214 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.81ms
2024-05-16 08:36:49,213 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.64ms
2024-05-16 08:37:19,215 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.10ms
2024-05-16 08:37:49,213 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.27ms
2024-05-16 08:38:19,433 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.93ms
2024-05-16 08:38:49,217 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.69ms
2024-05-16 08:39:19,218 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.91ms
2024-05-16 08:39:49,218 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.51ms
2024-05-16 08:40:19,218 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.10ms
2024-05-16 08:40:49,218 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.13ms
2024-05-16 08:41:19,219 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.04ms
2024-05-16 08:41:49,219 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.80ms
2024-05-16 08:42:19,219 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.81ms
2024-05-16 08:42:49,221 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.17ms
2024-05-16 08:43:19,221 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.76ms
2024-05-16 08:43:49,226 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.08ms
2024-05-16 08:44:19,223 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.00ms
2024-05-16 08:44:49,226 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.74ms
2024-05-16 08:45:19,228 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.55ms
2024-05-16 08:45:49,446 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.73ms
2024-05-16 08:46:19,230 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.09ms
2024-05-16 08:46:49,451 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.70ms
2024-05-16 08:47:19,229 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.53ms
2024-05-16 08:47:49,232 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.47ms
2024-05-16 08:48:19,230 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.73ms
2024-05-16 08:48:49,237 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.45ms
2024-05-16 08:49:20,258 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.84ms
2024-05-16 08:49:49,238 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.02ms
2024-05-16 08:50:19,235 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.42ms
2024-05-16 08:50:49,236 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.93ms
2024-05-16 08:51:19,238 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.85ms
2024-05-16 08:51:49,238 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.55ms
2024-05-16 08:52:19,241 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.81ms
2024-05-16 08:52:49,244 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.71ms
2024-05-16 08:53:19,244 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.42ms
2024-05-16 08:53:49,242 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.89ms
2024-05-16 08:54:19,242 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.45ms
2024-05-16 08:54:49,242 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.77ms
2024-05-16 08:55:19,242 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.74ms
2024-05-16 08:55:49,247 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.06ms
2024-05-16 08:56:19,243 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.93ms
2024-05-16 08:56:49,243 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.77ms
2024-05-16 08:57:19,248 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.78ms
2024-05-16 08:57:49,246 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.74ms
2024-05-16 08:58:19,487 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.37ms
2024-05-16 08:58:49,249 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.57ms
2024-05-16 08:59:19,262 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.57ms
2024-05-16 08:59:49,251 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.15ms
2024-05-16 09:00:19,251 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.02ms
2024-05-16 09:00:49,252 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.98ms
2024-05-16 09:01:19,254 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.21ms
2024-05-16 09:01:49,257 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.04ms
2024-05-16 09:02:19,255 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.90ms
2024-05-16 09:02:49,255 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.79ms
2024-05-16 09:03:19,257 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.25ms
2024-05-16 09:03:49,259 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.74ms
2024-05-16 09:04:19,266 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.25ms
2024-05-16 09:04:49,262 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.64ms
2024-05-16 09:05:19,262 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.62ms
2024-05-16 09:05:49,262 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.09ms
2024-05-16 09:06:19,265 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.69ms
2024-05-16 09:06:49,267 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.42ms
2024-05-16 09:07:19,268 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.33ms
2024-05-16 09:07:49,266 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.78ms
2024-05-16 09:08:19,273 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.99ms
2024-05-16 09:08:49,270 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.75ms
2024-05-16 09:09:19,269 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.97ms
2024-05-16 09:09:49,273 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.80ms
2024-05-16 09:10:19,274 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.64ms
2024-05-16 09:10:49,272 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.06ms
2024-05-16 09:11:19,274 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.28ms
2024-05-16 09:11:49,274 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.05ms
2024-05-16 09:12:19,288 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.63ms
2024-05-16 09:12:49,277 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.91ms
2024-05-16 09:13:19,281 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.87ms
2024-05-16 09:13:49,291 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.96ms
2024-05-16 09:14:19,278 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.33ms
2024-05-16 09:14:49,284 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.75ms
2024-05-16 09:15:19,303 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.80ms
2024-05-16 09:15:49,282 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.44ms
2024-05-16 09:16:19,512 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.34ms
2024-05-16 09:16:49,283 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.17ms
2024-05-16 09:17:19,284 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.13ms
2024-05-16 09:17:49,286 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.41ms
2024-05-16 09:18:19,285 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.04ms
2024-05-16 09:18:49,291 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.37ms
2024-05-16 09:19:19,290 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.53ms
2024-05-16 09:19:49,292 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.15ms
2024-05-16 09:20:19,295 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.22ms
2024-05-16 09:20:49,295 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.92ms
2024-05-16 09:21:19,294 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.64ms
2024-05-16 09:21:49,293 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.46ms
2024-05-16 09:22:19,297 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.07ms
2024-05-16 09:22:49,298 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.00ms
2024-05-16 09:23:19,297 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.97ms
2024-05-16 09:23:49,300 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.81ms
2024-05-16 09:24:19,300 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.51ms
2024-05-16 09:24:49,300 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.28ms
2024-05-16 09:25:19,303 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.44ms
2024-05-16 09:25:49,302 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.91ms
2024-05-16 09:26:19,302 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.72ms
2024-05-16 09:26:49,304 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.87ms
2024-05-16 09:27:19,304 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.38ms
2024-05-16 09:27:49,306 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.89ms
2024-05-16 09:28:19,308 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.57ms
2024-05-16 09:28:49,324 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.05ms
2024-05-16 09:29:19,306 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.64ms
2024-05-16 09:29:49,312 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.04ms
2024-05-16 09:30:19,311 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.64ms
2024-05-16 09:30:49,537 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.71ms
2024-05-16 09:31:19,314 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.23ms
2024-05-16 09:31:49,318 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 09:32:19,318 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.32ms
2024-05-16 09:32:49,329 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.46ms
2024-05-16 09:33:19,320 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.24ms
2024-05-16 09:33:49,322 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.78ms
2024-05-16 09:34:19,326 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.12ms
2024-05-16 09:34:49,328 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.23ms
2024-05-16 09:35:19,320 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.19ms
2024-05-16 09:35:49,322 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.96ms
2024-05-16 09:36:19,329 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.23ms
2024-05-16 09:36:49,323 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.79ms
2024-05-16 09:37:19,327 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.69ms
2024-05-16 09:37:49,326 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.24ms
2024-05-16 09:38:19,328 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.30ms
2024-05-16 09:38:49,327 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.60ms
2024-05-16 09:39:19,329 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.14ms
2024-05-16 09:39:49,334 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.34ms
2024-05-16 09:40:19,333 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.12ms
2024-05-16 09:40:49,340 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.32ms
2024-05-16 09:41:19,337 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.74ms
2024-05-16 09:41:49,338 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.84ms
2024-05-16 09:42:19,334 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.02ms
2024-05-16 09:42:49,336 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.28ms
2024-05-16 09:43:19,337 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.66ms
2024-05-16 09:43:49,339 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.40ms
2024-05-16 09:44:19,341 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.58ms
2024-05-16 09:44:49,339 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.30ms
2024-05-16 09:45:19,356 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.46ms
2024-05-16 09:45:49,339 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.12ms
2024-05-16 09:46:19,340 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.30ms
2024-05-16 09:46:49,343 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.48ms
2024-05-16 09:47:19,348 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.95ms
2024-05-16 09:47:49,342 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.75ms
2024-05-16 09:48:19,341 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 09:48:49,342 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.49ms
2024-05-16 09:49:19,342 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.35ms
2024-05-16 09:49:49,348 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.46ms
2024-05-16 09:50:19,343 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.10ms
2024-05-16 09:50:49,345 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.66ms
2024-05-16 09:51:19,349 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.65ms
2024-05-16 09:51:49,574 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.47ms
2024-05-16 09:52:19,347 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.00ms
2024-05-16 09:52:49,673 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 09:53:19,356 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.39ms
2024-05-16 09:53:49,357 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.67ms
2024-05-16 09:54:19,361 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.94ms
2024-05-16 09:54:49,352 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.63ms
2024-05-16 09:55:19,352 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.62ms
2024-05-16 09:55:49,356 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.45ms
2024-05-16 09:56:19,357 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.99ms
2024-05-16 09:56:49,356 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.25ms
2024-05-16 09:57:19,360 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.18ms
2024-05-16 09:57:49,362 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.59ms
2024-05-16 09:58:19,362 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.85ms
2024-05-16 09:58:49,360 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.37ms
2024-05-16 09:59:19,574 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.20ms
2024-05-16 09:59:49,363 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.58ms
2024-05-16 10:00:19,364 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.25ms
2024-05-16 10:00:49,363 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.84ms
2024-05-16 10:01:19,586 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.03ms
2024-05-16 10:01:49,371 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.77ms
2024-05-16 10:02:19,366 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.84ms
2024-05-16 10:02:49,368 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.19ms
2024-05-16 10:03:19,590 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.27ms
2024-05-16 10:03:49,368 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.72ms
2024-05-16 10:04:19,374 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.10ms
2024-05-16 10:04:49,370 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 10:05:19,367 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.46ms
2024-05-16 10:05:49,377 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.35ms
2024-05-16 10:06:19,583 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.86ms
2024-05-16 10:06:49,370 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.93ms
2024-05-16 10:07:19,372 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.74ms
2024-05-16 10:07:49,373 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.60ms
2024-05-16 10:08:19,371 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.87ms
2024-05-16 10:08:50,380 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.41ms
2024-05-16 10:09:19,372 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.31ms
2024-05-16 10:09:49,373 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.70ms
2024-05-16 10:10:19,377 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.11ms
2024-05-16 10:10:49,374 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.77ms
2024-05-16 10:11:19,376 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.02ms
2024-05-16 10:11:49,378 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.15ms
2024-05-16 10:12:19,397 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.41ms
2024-05-16 10:12:49,384 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.99ms
2024-05-16 10:13:19,384 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.97ms
2024-05-16 10:13:49,378 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.65ms
2024-05-16 10:14:19,379 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.93ms
2024-05-16 10:14:49,383 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.58ms
2024-05-16 10:15:19,380 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.77ms
2024-05-16 10:15:49,381 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.99ms
2024-05-16 10:16:19,385 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.54ms
2024-05-16 10:16:49,387 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.87ms
2024-05-16 10:17:19,386 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.81ms
2024-05-16 10:17:49,388 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.85ms
2024-05-16 10:18:19,387 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.12ms
2024-05-16 10:18:49,388 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.85ms
2024-05-16 10:19:19,389 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.86ms
2024-05-16 10:19:49,390 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.01ms
2024-05-16 10:20:19,392 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.94ms
2024-05-16 10:20:49,391 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.61ms
2024-05-16 10:21:19,393 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.17ms
2024-05-16 10:21:49,397 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.85ms
2024-05-16 10:22:19,398 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.09ms
2024-05-16 10:22:49,396 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.96ms
2024-05-16 10:23:19,395 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.94ms
2024-05-16 10:23:49,400 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.66ms
2024-05-16 10:24:19,402 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.63ms
2024-05-16 10:24:49,400 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.17ms
2024-05-16 10:25:19,401 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.60ms
2024-05-16 10:25:49,408 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.77ms
2024-05-16 10:26:19,401 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.97ms
2024-05-16 10:26:49,670 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.79ms
2024-05-16 10:27:20,417 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.04ms
2024-05-16 10:27:49,406 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.49ms
2024-05-16 10:28:19,408 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.23ms
2024-05-16 10:28:49,407 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.02ms
2024-05-16 10:29:19,410 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.80ms
2024-05-16 10:29:49,409 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.48ms
2024-05-16 10:30:19,412 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.02ms
2024-05-16 10:30:49,413 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.97ms
2024-05-16 10:31:19,415 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.43ms
2024-05-16 10:31:49,420 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.46ms
2024-05-16 10:32:19,424 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.38ms
2024-05-16 10:32:49,439 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 10:33:19,420 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.85ms
2024-05-16 10:33:49,416 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.19ms
2024-05-16 10:34:19,418 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.94ms
2024-05-16 10:34:49,419 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.58ms
2024-05-16 10:35:19,417 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.84ms
2024-05-16 10:35:49,422 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.57ms
2024-05-16 10:36:19,422 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.85ms
2024-05-16 10:36:49,419 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 10:37:19,421 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.13ms
2024-05-16 10:37:49,420 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.93ms
2024-05-16 10:38:19,420 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.84ms
2024-05-16 10:38:49,422 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.07ms
2024-05-16 10:39:19,425 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.85ms
2024-05-16 10:39:49,424 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.14ms
2024-05-16 10:40:19,425 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.75ms
2024-05-16 10:40:49,656 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.90ms
2024-05-16 10:41:19,427 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.92ms
2024-05-16 10:41:49,426 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.83ms
2024-05-16 10:42:19,431 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.42ms
2024-05-16 10:42:49,428 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.00ms
2024-05-16 10:43:19,429 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.70ms
2024-05-16 10:43:49,429 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.23ms
2024-05-16 10:44:19,431 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.23ms
2024-05-16 10:44:49,430 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.80ms
2024-05-16 10:45:19,442 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.15ms
2024-05-16 10:45:49,432 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.64ms
2024-05-16 10:46:19,433 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.87ms
2024-05-16 10:46:50,457 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.96ms
2024-05-16 10:47:19,436 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.53ms
2024-05-16 10:47:49,436 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.14ms
2024-05-16 10:48:19,437 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.16ms
2024-05-16 10:48:49,450 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.69ms
2024-05-16 10:49:19,664 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.86ms
2024-05-16 10:49:49,444 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.40ms
2024-05-16 10:50:19,460 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.55ms
2024-05-16 10:50:49,447 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.04ms
2024-05-16 10:51:19,452 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.39ms
2024-05-16 10:51:49,452 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.01ms
2024-05-16 10:52:19,444 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.85ms
2024-05-16 10:52:49,669 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 10:53:19,667 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.84ms
2024-05-16 10:53:49,445 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.79ms
2024-05-16 10:54:19,444 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.43ms
2024-05-16 10:54:49,446 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.60ms
2024-05-16 10:55:19,447 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.65ms
2024-05-16 10:55:49,448 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.83ms
2024-05-16 10:56:19,448 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.90ms
2024-05-16 10:56:49,449 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.27ms
2024-05-16 10:57:19,449 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.58ms
2024-05-16 10:57:49,447 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.58ms
2024-05-16 10:58:19,451 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.09ms
2024-05-16 10:58:49,669 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.83ms
2024-05-16 10:59:19,460 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.82ms
2024-05-16 10:59:49,454 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.45ms
2024-05-16 11:00:19,467 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.29ms
2024-05-16 11:00:49,455 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.86ms
2024-05-16 11:01:19,455 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.99ms
2024-05-16 11:01:49,455 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.46ms
2024-05-16 11:02:19,459 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.88ms
2024-05-16 11:02:49,456 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.43ms
2024-05-16 11:03:19,456 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.10ms
2024-05-16 11:03:49,459 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.25ms
2024-05-16 11:04:19,456 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.67ms
2024-05-16 11:04:49,456 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.83ms
2024-05-16 11:05:19,459 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.51ms
2024-05-16 11:05:49,456 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.22ms
2024-05-16 11:06:19,459 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.71ms
2024-05-16 11:06:49,460 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.29ms
2024-05-16 11:07:19,461 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.06ms
2024-05-16 11:07:49,462 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.43ms
2024-05-16 11:08:19,470 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.44ms
2024-05-16 11:08:49,468 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.75ms
2024-05-16 11:09:19,710 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.76ms
2024-05-16 11:09:49,464 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.08ms
2024-05-16 11:10:19,477 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.07ms
2024-05-16 11:10:49,464 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.41ms
2024-05-16 11:11:19,688 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.72ms
2024-05-16 11:11:49,465 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.97ms
2024-05-16 11:12:19,468 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.26ms
2024-05-16 11:12:49,468 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.20ms
2024-05-16 11:13:19,470 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.62ms
2024-05-16 11:13:49,469 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.52ms
2024-05-16 11:14:19,470 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.70ms
2024-05-16 11:14:49,692 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.73ms
2024-05-16 11:15:19,475 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.13ms
2024-05-16 11:15:49,476 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.24ms
2024-05-16 11:16:19,474 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.95ms
2024-05-16 11:16:49,476 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.43ms
2024-05-16 11:17:19,478 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.48ms
2024-05-16 11:17:49,689 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.71ms
2024-05-16 11:18:19,478 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.14ms
2024-05-16 11:18:49,480 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.39ms
2024-05-16 11:19:19,485 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.59ms
2024-05-16 11:19:49,484 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.66ms
2024-05-16 11:20:19,481 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.04ms
2024-05-16 11:20:49,483 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.36ms
2024-05-16 11:21:19,483 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.36ms
2024-05-16 11:21:49,493 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.36ms
2024-05-16 11:22:19,488 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.24ms
2024-05-16 11:22:49,485 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.54ms
2024-05-16 11:23:19,485 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.33ms
2024-05-16 11:23:49,485 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.34ms
2024-05-16 11:24:19,486 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.20ms
2024-05-16 11:24:49,708 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.72ms
2024-05-16 11:25:19,490 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.03ms
2024-05-16 11:25:49,492 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.30ms
2024-05-16 11:26:19,494 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.08ms
2024-05-16 11:26:49,492 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.27ms
2024-05-16 11:27:19,493 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.60ms
2024-05-16 11:27:50,537 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.88ms
2024-05-16 11:28:19,505 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.13ms
2024-05-16 11:28:49,497 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.06ms
2024-05-16 11:29:19,495 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.39ms
2024-05-16 11:29:49,497 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.32ms
2024-05-16 11:30:19,502 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.96ms
2024-05-16 11:30:49,499 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.71ms
2024-05-16 11:31:19,502 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.88ms
2024-05-16 11:31:49,501 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.14ms
2024-05-16 11:32:19,513 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.55ms
2024-05-16 11:32:49,505 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.13ms
2024-05-16 11:33:19,715 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.76ms
2024-05-16 11:33:49,504 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.79ms
2024-05-16 11:34:19,508 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.05ms
2024-05-16 11:34:49,506 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.29ms
2024-05-16 11:35:19,505 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.98ms
2024-05-16 11:35:49,504 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.36ms
2024-05-16 11:36:19,506 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.44ms
2024-05-16 11:36:49,508 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.97ms
2024-05-16 11:37:19,509 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.01ms
2024-05-16 11:37:49,510 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.52ms
2024-05-16 11:38:19,525 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.03ms
2024-05-16 11:38:49,510 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.54ms
2024-05-16 11:39:19,510 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.52ms
2024-05-16 11:39:49,515 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.99ms
2024-05-16 11:40:19,514 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.98ms
2024-05-16 11:40:49,514 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.51ms
2024-05-16 11:41:19,528 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.51ms
2024-05-16 11:41:49,532 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 20.34ms
2024-05-16 11:42:19,516 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.50ms
2024-05-16 11:42:49,518 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.32ms
2024-05-16 11:43:19,519 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.18ms
2024-05-16 11:43:49,523 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.76ms
2024-05-16 11:44:19,526 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.35ms
2024-05-16 11:44:49,545 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.77ms
2024-05-16 11:45:19,542 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.42ms
2024-05-16 11:45:49,527 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.42ms
2024-05-16 11:46:19,556 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.05ms
2024-05-16 11:46:49,532 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.49ms
2024-05-16 11:47:19,535 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.27ms
2024-05-16 11:47:49,532 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.82ms
2024-05-16 11:48:19,556 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.67ms
2024-05-16 11:48:49,528 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.73ms
2024-05-16 11:49:19,527 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.21ms
2024-05-16 11:49:49,529 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.80ms
2024-05-16 11:50:19,531 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.44ms
2024-05-16 11:50:49,540 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.43ms
2024-05-16 11:51:19,531 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.34ms
2024-05-16 11:51:49,532 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.42ms
2024-05-16 11:52:19,555 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.26ms
2024-05-16 11:52:49,566 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.01ms
2024-05-16 11:53:19,528 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.27ms
2024-05-16 11:53:49,538 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.00ms
2024-05-16 11:54:19,530 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.12ms
2024-05-16 11:54:49,529 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.52ms
2024-05-16 11:55:19,537 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.85ms
2024-05-16 11:55:49,537 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.60ms
2024-05-16 11:56:19,538 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.65ms
2024-05-16 11:56:49,545 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.28ms
2024-05-16 11:57:19,539 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.54ms
2024-05-16 11:57:49,538 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.92ms
2024-05-16 11:58:19,538 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.08ms
2024-05-16 11:58:49,699 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 11:59:19,542 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 7.38ms
2024-05-16 11:59:49,549 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.31ms
2024-05-16 12:00:19,551 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 10.14ms
2024-05-16 12:00:49,544 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.29ms
2024-05-16 12:01:19,563 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.01ms
2024-05-16 12:01:49,553 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.93ms
2024-05-16 12:02:19,549 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.11ms
2024-05-16 12:02:49,558 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.80ms
2024-05-16 12:03:19,569 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.16ms
2024-05-16 12:03:49,558 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 12:04:19,553 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.91ms
2024-05-16 12:04:49,559 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.44ms
2024-05-16 12:05:19,806 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.99ms
2024-05-16 12:05:49,562 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.10ms
2024-05-16 12:06:19,551 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.02ms
2024-05-16 12:06:49,551 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.82ms
2024-05-16 12:07:19,584 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.95ms
2024-05-16 12:07:49,553 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.75ms
2024-05-16 12:08:19,558 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.86ms
2024-05-16 12:08:49,575 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.07ms
2024-05-16 12:09:19,563 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.01ms
2024-05-16 12:09:49,578 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.51ms
2024-05-16 12:10:19,557 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.29ms
2024-05-16 12:10:49,558 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 12:11:19,562 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.12ms
2024-05-16 12:11:49,558 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.02ms
2024-05-16 12:12:19,566 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.35ms
2024-05-16 12:12:49,562 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.23ms
2024-05-16 12:13:19,561 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.89ms
2024-05-16 12:13:49,576 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.29ms
2024-05-16 12:14:19,571 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.44ms
2024-05-16 12:14:49,564 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.50ms
2024-05-16 12:15:19,565 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.11ms
2024-05-16 12:15:49,567 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 12:16:20,358 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.92ms
2024-05-16 12:16:49,568 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.14ms
2024-05-16 12:17:19,569 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 12:17:49,568 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.63ms
2024-05-16 12:18:19,582 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.86ms
2024-05-16 12:18:49,573 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.24ms
2024-05-16 12:19:19,570 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.71ms
2024-05-16 12:19:49,573 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.05ms
2024-05-16 12:20:19,570 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 12:20:49,576 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.25ms
2024-05-16 12:21:19,574 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.79ms
2024-05-16 12:21:49,571 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.06ms
2024-05-16 12:22:19,578 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.89ms
2024-05-16 12:22:49,579 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.00ms
2024-05-16 12:23:19,585 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.00ms
2024-05-16 12:23:49,619 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.03ms
2024-05-16 12:24:19,590 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.12ms
2024-05-16 12:24:49,576 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.99ms
2024-05-16 12:25:19,578 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.60ms
2024-05-16 12:25:49,792 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.38ms
2024-05-16 12:26:19,576 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.15ms
2024-05-16 12:26:49,585 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.37ms
2024-05-16 12:27:19,578 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.15ms
2024-05-16 12:27:49,578 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.14ms
2024-05-16 12:28:19,578 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.16ms
2024-05-16 12:28:49,579 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.04ms
2024-05-16 12:29:19,581 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.86ms
2024-05-16 12:29:49,579 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.01ms
2024-05-16 12:30:19,579 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.97ms
2024-05-16 12:30:49,583 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.21ms
2024-05-16 12:31:19,581 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.09ms
2024-05-16 12:31:49,585 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.31ms
2024-05-16 12:32:19,584 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.75ms
2024-05-16 12:32:49,584 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.89ms
2024-05-16 12:33:19,584 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.99ms
2024-05-16 12:33:49,805 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.02ms
2024-05-16 12:34:19,585 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.17ms
2024-05-16 12:34:49,589 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.24ms
2024-05-16 12:35:19,590 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.19ms
2024-05-16 12:35:49,586 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.19ms
2024-05-16 12:36:19,588 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.03ms
2024-05-16 12:36:49,600 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.88ms
2024-05-16 12:37:19,592 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.22ms
2024-05-16 12:37:49,593 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 12:38:19,594 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.44ms
2024-05-16 12:38:49,596 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.00ms
2024-05-16 12:39:19,599 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.10ms
2024-05-16 12:39:49,604 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.14ms
2024-05-16 12:40:19,604 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.67ms
2024-05-16 12:40:49,615 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.74ms
2024-05-16 12:41:19,609 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.78ms
2024-05-16 12:41:49,614 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 12:42:19,615 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 12:42:49,604 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.39ms
2024-05-16 12:43:19,604 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.80ms
2024-05-16 12:43:49,605 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.05ms
2024-05-16 12:44:19,610 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.88ms
2024-05-16 12:44:49,606 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.08ms
2024-05-16 12:45:19,607 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.00ms
2024-05-16 12:45:49,609 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.84ms
2024-05-16 12:46:19,609 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.02ms
2024-05-16 12:46:49,611 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.88ms
2024-05-16 12:47:19,611 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.05ms
2024-05-16 12:47:49,610 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.15ms
2024-05-16 12:48:19,610 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 12:48:49,628 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.16ms
2024-05-16 12:49:19,615 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.28ms
2024-05-16 12:49:49,619 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.99ms
2024-05-16 12:50:19,616 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.20ms
2024-05-16 12:50:49,615 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.54ms
2024-05-16 12:51:19,615 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.69ms
2024-05-16 12:51:49,616 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.00ms
2024-05-16 12:52:19,621 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.89ms
2024-05-16 12:52:49,621 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.03ms
2024-05-16 12:53:19,619 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.27ms
2024-05-16 12:53:49,619 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 12:54:19,625 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.09ms
2024-05-16 12:54:49,629 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.01ms
2024-05-16 12:55:19,622 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.05ms
2024-05-16 12:55:49,622 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.96ms
2024-05-16 12:56:19,631 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.90ms
2024-05-16 12:56:49,628 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 12:57:19,628 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.85ms
2024-05-16 12:57:49,628 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.03ms
2024-05-16 12:58:19,630 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.17ms
2024-05-16 12:58:49,632 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.88ms
2024-05-16 12:59:19,637 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.13ms
2024-05-16 12:59:49,637 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.96ms
2024-05-16 13:00:19,641 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.84ms
2024-05-16 13:00:49,647 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.10ms
2024-05-16 13:01:19,637 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.61ms
2024-05-16 13:01:49,633 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.69ms
2024-05-16 13:02:19,638 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.11ms
2024-05-16 13:02:49,637 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.90ms
2024-05-16 13:03:19,636 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.32ms
2024-05-16 13:03:49,636 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.82ms
2024-05-16 13:04:19,636 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.99ms
2024-05-16 13:04:49,638 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.37ms
2024-05-16 13:05:19,639 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.08ms
2024-05-16 13:05:49,639 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.28ms
2024-05-16 13:06:19,640 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.29ms
2024-05-16 13:06:49,642 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.85ms
2024-05-16 13:07:19,641 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.99ms
2024-05-16 13:07:49,645 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.81ms
2024-05-16 13:08:19,642 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.01ms
2024-05-16 13:08:49,647 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.37ms
2024-05-16 13:09:19,645 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.12ms
2024-05-16 13:09:49,645 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.51ms
2024-05-16 13:10:19,655 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 13:10:49,650 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.83ms
2024-05-16 13:11:19,651 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.83ms
2024-05-16 13:11:49,650 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.84ms
2024-05-16 13:12:19,650 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.83ms
2024-05-16 13:12:49,650 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.31ms
2024-05-16 13:13:19,651 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.22ms
2024-05-16 13:13:49,651 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.78ms
2024-05-16 13:14:19,652 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.12ms
2024-05-16 13:14:49,654 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.30ms
2024-05-16 13:15:19,658 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.52ms
2024-05-16 13:15:49,659 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.85ms
2024-05-16 13:16:19,661 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.86ms
2024-05-16 13:16:49,659 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.27ms
2024-05-16 13:17:19,658 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.11ms
2024-05-16 13:17:49,657 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.10ms
2024-05-16 13:18:19,661 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.18ms
2024-05-16 13:18:49,658 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.18ms
2024-05-16 13:19:19,664 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.27ms
2024-05-16 13:19:49,671 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.28ms
2024-05-16 13:20:19,661 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.03ms
2024-05-16 13:20:49,663 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.25ms
2024-05-16 13:21:19,663 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.35ms
2024-05-16 13:21:49,666 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.25ms
2024-05-16 13:22:19,668 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.77ms
2024-05-16 13:22:49,666 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.12ms
2024-05-16 13:23:19,672 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.45ms
2024-05-16 13:23:49,670 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.43ms
2024-05-16 13:24:19,670 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.31ms
2024-05-16 13:24:49,671 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 13:25:19,674 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.56ms
2024-05-16 13:25:49,674 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.45ms
2024-05-16 13:26:19,674 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.20ms
2024-05-16 13:26:49,678 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.94ms
2024-05-16 13:27:19,678 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.28ms
2024-05-16 13:27:49,678 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.32ms
2024-05-16 13:28:19,685 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.29ms
2024-05-16 13:28:49,898 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.90ms
2024-05-16 13:29:19,678 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 13:29:49,681 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.44ms
2024-05-16 13:30:19,684 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.24ms
2024-05-16 13:30:49,681 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.19ms
2024-05-16 13:31:19,690 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.06ms
2024-05-16 13:31:49,684 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.45ms
2024-05-16 13:32:19,685 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.57ms
2024-05-16 13:32:49,684 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.80ms
2024-05-16 13:33:19,683 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.83ms
2024-05-16 13:33:49,683 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.21ms
2024-05-16 13:34:19,683 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.05ms
2024-05-16 13:34:49,685 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.06ms
2024-05-16 13:35:19,689 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.85ms
2024-05-16 13:35:49,687 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.34ms
2024-05-16 13:36:19,688 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 13:36:49,693 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.18ms
2024-05-16 13:37:19,692 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.01ms
2024-05-16 13:37:49,692 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.28ms
2024-05-16 13:38:19,695 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.97ms
2024-05-16 13:38:49,696 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.49ms
2024-05-16 13:39:19,700 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.17ms
2024-05-16 13:39:49,695 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 13:40:19,695 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.03ms
2024-05-16 13:40:49,698 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.67ms
2024-05-16 13:41:19,699 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.81ms
2024-05-16 13:41:49,700 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.04ms
2024-05-16 13:42:19,697 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.21ms
2024-05-16 13:42:49,702 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.24ms
2024-05-16 13:43:19,700 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.25ms
2024-05-16 13:43:49,699 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.86ms
2024-05-16 13:44:19,703 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.02ms
2024-05-16 13:44:49,703 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.89ms
2024-05-16 13:45:19,702 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.06ms
2024-05-16 13:45:49,702 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.90ms
2024-05-16 13:46:19,705 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.00ms
2024-05-16 13:46:49,707 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 13:47:19,708 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.89ms
2024-05-16 13:47:49,707 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.33ms
2024-05-16 13:48:19,706 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.04ms
2024-05-16 13:48:49,707 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.98ms
2024-05-16 13:49:19,716 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.07ms
2024-05-16 13:49:49,710 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.05ms
2024-05-16 13:50:19,710 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.74ms
2024-05-16 13:50:49,709 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.95ms
2024-05-16 13:51:19,710 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.39ms
2024-05-16 13:51:49,712 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.04ms
2024-05-16 13:52:19,714 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.80ms
2024-05-16 13:52:49,714 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.18ms
2024-05-16 13:53:19,713 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.26ms
2024-05-16 13:53:49,713 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.25ms
2024-05-16 13:54:19,714 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.00ms
2024-05-16 13:54:49,720 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.70ms
2024-05-16 13:55:19,715 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.17ms
2024-05-16 13:55:49,718 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.18ms
2024-05-16 13:56:19,721 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.50ms
2024-05-16 13:56:49,721 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.89ms
2024-05-16 13:57:19,724 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.35ms
2024-05-16 13:57:49,722 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.35ms
2024-05-16 13:58:19,726 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.17ms
2024-05-16 13:58:49,723 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.81ms
2024-05-16 13:59:19,725 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.63ms
2024-05-16 13:59:49,726 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.86ms
2024-05-16 14:00:19,726 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.02ms
2024-05-16 14:00:50,757 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.37ms
2024-05-16 14:01:19,727 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.04ms
2024-05-16 14:01:49,736 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 8.62ms
2024-05-16 14:02:19,729 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 3.97ms
2024-05-16 14:02:49,734 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.56ms
2024-05-16 14:03:19,737 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.15ms
2024-05-16 14:03:49,733 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.96ms
2024-05-16 14:04:19,735 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.75ms
2024-05-16 14:04:49,737 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 6.76ms
2024-05-16 14:05:19,734 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.27ms
2024-05-16 14:05:49,742 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 11.46ms
2024-05-16 14:06:19,742 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 10.60ms
2024-05-16 14:06:49,740 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 4.81ms
2024-05-16 14:07:19,744 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.01ms
2024-05-16 14:07:49,744 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.71ms
2024-05-16 14:08:19,797 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.47ms
2024-05-16 14:08:32,574 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.22
2024-05-16 14:08:32,577 [application.py:log_request()] - 101 GET /websocket (192.168.1.22) [_TRUSTED_USER_] 4.32ms
2024-05-16 14:08:32,578 [websockets.py:open()] - Websocket Opened: ID: 547558036336, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.28
2024-05-16 14:08:32,625 [websockets.py:_handle_identify()] - Websocket 547558036336 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-05-16 14:08:37,271 [websockets.py:write_to_socket()] - Websocket closed while writing: 547585879920
2024-05-16 14:08:37,274 [websockets.py:on_close()] - Websocket Closed: ID: 547585879920 Close Code: None, Close Reason: None, Pong Time Elapsed: 1.26
2024-05-16 14:08:42,451 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 4.15ms
2024-05-16 14:08:42,452 [websockets.py:open()] - Websocket Opened: ID: 547557049488, Proxied: False, User Agent: , Host Name: 127.0.0.1
2024-05-16 14:08:42,586 [websockets.py:_handle_identify()] - Websocket 547557049488 Client Identified - Name: KlipperScreen, Version: v0.4.0-73-g1afc67b, Type: display
2024-05-16 14:08:43,467 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
2024-05-16 14:08:46,996 [websockets.py:on_close()] - Websocket Closed: ID: 547558036336 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 4.41
2024-05-16 14:08:47,183 [application.py:log_request()] - 101 GET /websocket (192.168.1.22) [_TRUSTED_USER_] 3.63ms
2024-05-16 14:08:47,184 [websockets.py:open()] - Websocket Opened: ID: 547585857040, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.28
2024-05-16 14:08:47,192 [websockets.py:_handle_identify()] - Websocket 547585857040 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-05-16 14:08:49,745 [application.py:log_request()] - 404 GET /server/files/metadata?filename= (192.168.1.149) [_TRUSTED_USER_] 5.54ms
2024-05-16 14:08:55,298 [websockets.py:on_close()] - Websocket Closed: ID: 547557049488 Close Code: None, Close Reason: None, Pong Time Elapsed: 2.84
2024-05-16 14:08:55,313 [server.py:_handle_term_signal()] - Exiting with signal SIGTERM
2024-05-16 14:08:55,500 [websockets.py:write_to_socket()] - Websocket closed while writing: 547585926288
2024-05-16 14:08:55,500 [websockets.py:write_to_socket()] - Websocket closed while writing: 547585857040
2024-05-16 14:08:55,502 [websockets.py:on_close()] - Websocket Closed: ID: 547585857040 Close Code: 1001, Close Reason: Server Shutdown, Pong Time Elapsed: 8.32
2024-05-16 14:08:55,505 [websockets.py:on_close()] - Websocket Closed: ID: 547585926288 Close Code: 1001, Close Reason: Server Shutdown, Pong Time Elapsed: 9.47
2024-05-16 14:08:55,512 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-05-16 14:08:57,322 [database.py:close()] - Database statistics:

announcements:
psize: 4096
depth: 0
branch_pages: 0
leaf_pages: 0
overflow_pages: 0
entries: 0
authorized_users:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 1
gcode_metadata:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 3
history:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 4
overflow_pages: 0
entries: 12
mainsail:
psize: 4096
depth: 2
branch_pages: 1
leaf_pages: 2
overflow_pages: 0
entries: 9
moonraker:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 0
entries: 7
update_manager:
psize: 4096
depth: 1
branch_pages: 0
leaf_pages: 1
overflow_pages: 6
entries: 5
2024-05-16 14:08:57,669 [server.py:main()] - Server Shutdown
-------------------- Log Start | Thu May 16 13:09:20 2024 --------------------
data_path: /home/pi/printer_data
is_default_data_path: False
config_file: /home/pi/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: True
instance_uuid: 215a8ff9406149558f7a7b86cec4267d
unix_socket_path: /home/pi/printer_data/comms/moonraker.sock
software_version: v0.8.0-268-ga23187b
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/pi/printer_data/logs/moonraker.log
python_version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
launch_args: /home/pi/moonraker-env/bin/python /home/pi/moonraker/moonraker/__main__.py
msgspec_enabled: False
uvloop_enabled: False
2024-05-16 14:09:20,254 [confighelper.py:read_file()] - Configuration File '/home/pi/printer_data/config/moonraker.conf' parsed, total size: 1762 B
2024-05-16 14:09:20,256 [server.py:add_log_rollover_item()] - 
#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
enable_debug_logging = False
max_upload_size = 1024
klippy_uds_address = home/pi/printer_data/comms/klippy.sock

[file_manager]
config_path = ~/printer_data/config
enable_object_processing = True

[authorization]
cors_domains = 
	https://my.mainsail.xyz
	http://my.mainsail.xyz
	http://app.fluidd.xyz
	http://*.local
	http://*.lan
trusted_clients = 
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.1.0/24
	172.16.0.0/24
	172.17.0.15:80
	FE80::/10
	::1/128

[octoprint_compat]

[history]

[update_manager]
refresh_interval = 168
enable_auto_refresh = True
enable_repo_debug = True

[update_manager mainsail]
type = web
repo = mainsail-crew/mainsail
path = ~/mainsail

[update_manager beacon]
type = git_repo
channel = dev
path = ~/beacon_klipper
origin = https://github.com/beacon3d/beacon_klipper.git
env = ~/klippy-env/bin/python
requirements = requirements.txt
install_script = install.sh
is_system_service = False
managed_services = klipper
info_tags = 
	desc=Beacon Surface Scanner

[wled lights]
type = http
address = 192.168.1.7
initial_preset = 2
initial_red = 1
initial_green = 1
initial_blue = 1
chain_count = 115

#################################################################
All Configuration Files:
/home/pi/printer_data/config/moonraker.conf
#################################################################
2024-05-16 14:09:20,257 [server.py:add_warning()] - [server]: Option 'enable_debug_logging' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
2024-05-16 14:09:20,814 [server.py:load_component()] - Component (secrets) loaded
2024-05-16 14:09:20,838 [server.py:load_component()] - Component (template) loaded
2024-05-16 14:09:20,860 [server.py:load_component()] - Component (klippy_connection) loaded
2024-05-16 14:09:22,578 [server.py:load_component()] - Component (application) loaded
2024-05-16 14:09:22,641 [server.py:load_component()] - Component (websockets) loaded
2024-05-16 14:09:22,788 [server.py:load_component()] - Component (dbus_manager) loaded
2024-05-16 14:09:22,865 [server.py:add_log_rollover_item()] - 
Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 4
2024-05-16 14:09:22,889 [server.py:load_component()] - Component (database) loaded
2024-05-16 14:09:22,931 [file_manager.py:__init__()] - Using File System Observer: inotify
2024-05-16 14:09:23,029 [server.py:add_warning()] - [file_manager]: Option 'config_path' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
2024-05-16 14:09:23,038 [server.py:load_component()] - Component (file_manager) loaded
2024-05-16 14:09:23,049 [server.py:load_component()] - Component (klippy_apis) loaded
2024-05-16 14:09:23,637 [server.py:add_log_rollover_item()] - 
System Info:

***python***
  version: (3, 9, 2, 'final', 0)
  version_string: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 735411d3
  hardware_desc: BCM2835
  model: Raspberry Pi 3 Model B Plus Rev 1.3
  total_memory: 880332
  memory_units: kB

***sd_info***
  manufacturer_id: 27
  manufacturer: Unknown
  oem_id: 5048
  product_name: SD32G
  product_revision: 6.0
  serial_number: 79550c64
  manufacturer_date: 8/2021
  capacity: 28.8 GiB
  total_bytes: 30941380608

***distribution***
  name: Debian GNU/Linux 11 (bullseye)
  id: debian
  version: 11
  version_parts: {'major': '11', 'minor': '', 'build_number': ''}
  like: 
  codename: bullseye
  release_info: {'name': 'MainsailOS', 'version_id': '1.3.2', 'codename': 'bullseye', 'id': 'mainsailos'}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
2024-05-16 14:09:23,645 [server.py:load_component()] - Component (shell_command) loaded
2024-05-16 14:09:23,646 [machine.py:__init__()] - Using System Provider: systemd_dbus
2024-05-16 14:09:23,660 [server.py:load_component()] - Component (machine) loaded
2024-05-16 14:09:23,667 [server.py:load_component()] - Component (data_store) loaded
2024-05-16 14:09:23,675 [proc_stats.py:__init__()] - Detected 'vcgencmd', throttle checking enabled
2024-05-16 14:09:23,677 [server.py:load_component()] - Component (proc_stats) loaded
2024-05-16 14:09:23,680 [server.py:load_component()] - Component (job_state) loaded
2024-05-16 14:09:23,690 [server.py:load_component()] - Component (job_queue) loaded
2024-05-16 14:09:23,709 [server.py:load_component()] - Component (http_client) loaded
2024-05-16 14:09:23,721 [server.py:load_component()] - Component (announcements) loaded
2024-05-16 14:09:23,729 [server.py:load_component()] - Component (webcam) loaded
2024-05-16 14:09:23,735 [server.py:load_component()] - Component (extensions) loaded
2024-05-16 14:09:23,809 [server.py:add_warning()] - [authorization]: Invalid domain name '172.17.0.15:80' in option 'trusted_clients'
2024-05-16 14:09:23,811 [authorization.py:__init__()] - Authorization Configuration Loaded
Trusted Clients:
10.0.0.0/8
127.0.0.0/8
169.254.0.0/16
172.16.0.0/12
192.168.1.0/24
172.16.0.0/24
fe80::/10
::1/128
CORS Domains:
https://my\.mainsail\.xyz
http://my\.mainsail\.xyz
http://app\.fluidd\.xyz
http://.*\.local
http://.*\.lan
2024-05-16 14:09:23,820 [server.py:load_component()] - Component (authorization) loaded
2024-05-16 14:09:23,836 [server.py:load_component()] - Component (octoprint_compat) loaded
2024-05-16 14:09:23,853 [server.py:load_component()] - Component (history) loaded
2024-05-16 14:09:23,965 [server.py:add_warning()] - [update_manager]: Option 'enable_repo_debug' is deprecated, see the configuration documention at https://moonraker.readthedocs.io/en/latest/configuration/
2024-05-16 14:09:23,970 [base_deploy.py:log_info()] - Git Repo moonraker: Detected virtualenv: /home/pi/moonraker-env
2024-05-16 14:09:23,990 [base_deploy.py:log_info()] - Git Repo klipper: Detected virtualenv: /home/pi/klippy-env
2024-05-16 14:09:23,998 [base_deploy.py:log_info()] - Git Repo beacon: Option 'env' is deprecated, use 'virtualenv' instead.
2024-05-16 14:09:24,000 [base_deploy.py:log_info()] - Git Repo beacon: Detected virtualenv: /home/pi/klippy-env
2024-05-16 14:09:24,010 [server.py:load_component()] - Component (update_manager) loaded
2024-05-16 14:09:24,039 [wled.py:__init__()] - WLED component loading strips: ['wled lights']
2024-05-16 14:09:24,039 [wled.py:__init__()] - WLED strip: lights
2024-05-16 14:09:24,046 [server.py:load_component()] - Component (wled) loaded
2024-05-16 14:09:24,049 [server.py:_initialize_component()] - Performing Component Post Init: [dbus_manager]
2024-05-16 14:09:24,085 [server.py:_initialize_component()] - Performing Component Post Init: [file_manager]
2024-05-16 14:09:24,137 [server.py:_initialize_component()] - Performing Component Post Init: [machine]
2024-05-16 14:09:24,138 [machine.py:validation_init()] - Installation version in database up to date
2024-05-16 14:09:25,033 [machine.py:check_virt_status()] - No Virtualization Detected
2024-05-16 14:09:25,058 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.1.28
2024-05-16 14:09:25,064 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.28
2024-05-16 14:09:25,243 [server.py:add_log_rollover_item()] - 
Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', 'network-online.target', 'system.slice']
**After=['network-online.target', 'systemd-journald.socket', 'sysinit.target', 'basic.target', 'system.slice', 'klipper.service']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/pi/printer_data/systemd/moonraker.env
**ExecStart=/home/pi/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=pi
2024-05-16 14:09:25,243 [server.py:_initialize_component()] - Performing Component Post Init: [proc_stats]
2024-05-16 14:09:25,244 [server.py:_initialize_component()] - Performing Component Post Init: [announcements]
2024-05-16 14:09:25,250 [server.py:_initialize_component()] - Performing Component Post Init: [webcam]
2024-05-16 14:09:25,251 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.1.28
2024-05-16 14:09:25,252 [server.py:_initialize_component()] - Performing Component Post Init: [klippy_connection]
2024-05-16 14:09:25,253 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['system.slice', 'sysinit.target', '-.mount']
**After=['basic.target', 'system.slice', 'network-online.target', '-.mount', 'sysinit.target', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/pi/printer_data/systemd/klipper.env
**ExecStart=/home/pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=pi
2024-05-16 14:09:25,253 [server.py:_initialize_component()] - Performing Component Post Init: [authorization]
2024-05-16 14:09:25,254 [server.py:_initialize_component()] - Performing Component Post Init: [history]
2024-05-16 14:09:25,263 [server.py:_initialize_component()] - Performing Component Post Init: [update_manager]
2024-05-16 14:09:25,268 [server.py:_initialize_component()] - Performing Component Post Init: [wled]
2024-05-16 14:09:26,480 [base_deploy.py:log_info()] - PackageDeploy: PackageKit Provider Configured
2024-05-16 14:09:26,531 [git_deploy.py:log_repo_info()] - Git Repo moonraker Detected:
Owner: Arksine
Repository Name: moonraker
Path: /home/pi/moonraker
Remote: origin
Branch: master
Remote URL: https://github.com/Arksine/moonraker.git
Recovery URL: https://github.com/Arksine/moonraker.git
Current Commit SHA: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Upstream Commit SHA: ba9428558adc70ed8cb3cdcea1723358ead23741
Current Version: v0.8.0-268-ga23187b4
Upstream Version: v0.8.0-354-gba942855
Rollback Commit: a23187b4afa632da8a90cb9eae83f0f6a5eec903
Rollback Branch: master
Rollback Version: v0.8.0-268-ga23187b4
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 86
Diverged: False
Repo Warnings:
  Repo has untracked source files: ['moonraker/components/timelapse.py']
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
2024-05-16 14:09:26,585 [git_deploy.py:log_repo_info()] - Git Repo klipper Detected:
Owner: Klipper3d
Repository Name: klipper
Path: /home/pi/klipper
Remote: origin
Branch: master
Remote URL: https://github.com/Klipper3d/klipper.git
Recovery URL: https://github.com/Klipper3d/klipper.git
Current Commit SHA: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Upstream Commit SHA: 434770eaf9d382cccba203a3475ace2dc0653d7b
Current Version: v0.12.0-85-gd785b396
Upstream Version: v0.12.0-179-g434770ea
Rollback Commit: d785b396a72b57c073ce5bdf7a9d5e9fe39fc914
Rollback Branch: master
Rollback Version: v0.12.0-85-gd785b396
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 94
Diverged: False
Repo Warnings:
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
2024-05-16 14:09:26,600 [web_deploy.py:_log_client_info()] - Web Client mainsail Detected:
Repo: mainsail-crew/mainsail
Channel: stable
Path: /home/pi/mainsail
Local Version: v2.9.1
Remote Version: v2.11.2
Valid: True
Fallback Client Detected: False
Pre-release: False
Download Url: https://github.com/mainsail-crew/mainsail/releases/download/v2.11.2/mainsail.zip
Download Size: 2114797
Content Type: application/zip
Rollback Version: v2.9.1
Rollback Repo: mainsail-crew/mainsail
2024-05-16 14:09:26,657 [git_deploy.py:log_repo_info()] - Git Repo beacon Detected:
Owner: beacon3d
Repository Name: beacon_klipper
Path: /home/pi/beacon_klipper
Remote: origin
Branch: master
Remote URL: https://github.com/beacon3d/beacon_klipper.git
Recovery URL: https://github.com/beacon3d/beacon_klipper.git
Current Commit SHA: b89bbbec0d94c92ba709a1da283afd0a5eb2c19e
Upstream Commit SHA: b89bbbec0d94c92ba709a1da283afd0a5eb2c19e
Current Version: v1.0.0-35-gb89bbbec
Upstream Version: v1.0.0-35-gb89bbbec
Rollback Commit: b89bbbec0d94c92ba709a1da283afd0a5eb2c19e
Rollback Branch: master
Rollback Version: v1.0.0-35-gb89bbbec
Is Dirty: False
Is Detached: False
Is Shallow: False
Commits Behind Count: 0
Diverged: False
Repo Warnings:
  Multiple instances of Moonraker managing this repo:
  moonraker@37c893792c5e4af3a65b8dfa892580af
  moonraker@215a8ff9406149558f7a7b86cec4267d
2024-05-16 14:09:26,659 [base_deploy.py:log_info()] - PackageKit: Next refresh in: 2 Days, 16 Hours, 40 Minutes, 40 Seconds
2024-05-16 14:09:26,659 [base_deploy.py:log_info()] - Git Repo moonraker: Next refresh in: 2 Days, 16 Hours, 40 Minutes, 51 Seconds
2024-05-16 14:09:26,659 [base_deploy.py:log_info()] - Git Repo klipper: Next refresh in: 2 Days, 16 Hours, 41 Minutes, 2 Seconds
2024-05-16 14:09:26,659 [base_deploy.py:log_info()] - Web Client mainsail: Next refresh in: 3 Days, 1 Hour, 45 Minutes, 13 Seconds
2024-05-16 14:09:26,660 [base_deploy.py:log_info()] - Git Repo beacon: Next refresh in: 3 Days, 1 Hour, 59 Minutes, 49 Seconds
2024-05-16 14:09:31,352 [wled.py:_send_wled_command()] - WLED: Error Timeout while connecting
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/wled.py", line 123, in _send_wled_command
    await self.send_wled_command_impl(state)
  File "/home/pi/moonraker/moonraker/components/wled.py", line 302, in send_wled_command_impl
    response = await self.client.fetch(request)
tornado.simple_httpclient.HTTPTimeoutError: Timeout while connecting
2024-05-16 14:09:31,352 [wled.py:component_init()] - WLED: Error Timeout while connecting
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/wled.py", line 123, in _send_wled_command
    await self.send_wled_command_impl(state)
  File "/home/pi/moonraker/moonraker/components/wled.py", line 302, in send_wled_command_impl
    response = await self.client.fetch(request)
tornado.simple_httpclient.HTTPTimeoutError: Timeout while connecting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/wled.py", line 423, in component_init
    await ret
  File "/home/pi/moonraker/moonraker/components/wled.py", line 89, in initialize
    await self.wled_on(self.initial_preset)
  File "/home/pi/moonraker/moonraker/components/wled.py", line 145, in wled_on
    await self._send_wled_command({"on": True, "ps": preset})
  File "/home/pi/moonraker/moonraker/components/wled.py", line 130, in _send_wled_command
    raise self.server.error(msg)
moonraker.utils.ServerError: WLED: Error Timeout while connecting
2024-05-16 14:09:31,359 [extensions.py:start_unix_server()] - Creating Unix Domain Socket at '/home/pi/printer_data/comms/moonraker.sock'
2024-05-16 14:09:31,362 [server.py:start_server()] - Starting Moonraker on (0.0.0.0, 7125), Hostname: mainsailos
2024-05-16 14:09:31,368 [application.py:listen()] - SSL Certificate/Key not configured, aborting HTTPS Server startup
2024-05-16 14:09:31,622 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-05-16 14:09:31,776 [server.py:add_log_rollover_item()] - 
Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', '-.mount', 'system.slice']
**After=['network-online.target', 'sysinit.target', 'basic.target', '-.mount', 'system.slice', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/pi/printer_data/systemd/klipper.env
**ExecStart=/home/pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=pi
2024-05-16 14:09:32,033 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-85-gd785b396-dirty
2024-05-16 14:09:32,070 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-05-16 14:09:32,075 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-05-16 14:09:32,321 [job_state.py:_handle_started()] - Job state initialized: standby
2024-05-16 14:09:32,603 [klippy_connection.py:_check_ready()] - Klippy ready
2024-05-16 14:09:32,928 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 127.0.0.1
2024-05-16 14:09:32,947 [application.py:log_request()] - 101 GET /websocket?token= (127.0.0.1) [_TRUSTED_USER_] 4.24ms
2024-05-16 14:09:32,948 [websockets.py:open()] - Websocket Opened: ID: 547918527984, Proxied: False, User Agent: , Host Name: 127.0.0.1
2024-05-16 14:09:33,015 [websockets.py:_handle_identify()] - Websocket 547918527984 Client Identified - Name: KlipperScreen, Version: v0.4.0-73-g1afc67b, Type: display
2024-05-16 14:09:33,075 [data_store.py:_init_sensors()] - Configuring available sensors: ['heater_bed', 'temperature_sensor mcu', 'temperature_sensor raspi', 'temperature_sensor toolhead', 'temperature_sensor chamber', 'temperature_sensor beacon_coil', 'extruder']
2024-05-16 14:09:33,129 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.149
2024-05-16 14:09:33,168 [application.py:log_request()] - 404 GET /server/files/metadata?filename=unknown (192.168.1.149) [_TRUSTED_USER_] 40.67ms
2024-05-16 14:09:33,838 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.22
2024-05-16 14:09:33,842 [application.py:log_request()] - 101 GET /websocket (192.168.1.22) [_TRUSTED_USER_] 6.66ms
2024-05-16 14:09:33,843 [websockets.py:open()] - Websocket Opened: ID: 547918527552, Proxied: True, User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36, Host Name: 192.168.1.28
2024-05-16 14:09:33,880 [websockets.py:_handle_identify()] - Websocket 547918527552 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-05-16 14:09:33,997 [file_manager.py:get_file_list()] - Updating File List <gcodes>...
